version: '3.9'

services:
  postgres:
    image: postgres:latest
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - postgresdata:/data/postgres
    restart: unless-stopped

volumes:
  postgresdata:
