name: Deploy Prod to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v4.0.1
        with:
          node-version: '18'  # Using Node.js version 18
          cache: 'pnpm'  # Caching dependencies for faster builds

      - name: Install pnpm
        run: npm install -g pnpm
      
      - name: use pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10
          
      - name: get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Installing pnpm
        run: pnpm install --frozen-lockfile

      - name: Linting check
        run: pnpm run lint

      - name: Building application
        run: pnpm run build
        env:
          NODE_ENV: "production"
          SERP_API_KEY: ${{secrets.SERP_API_KEY}}
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          APP_JWT_SECRET: ${{secrets.APP_JWT_SECRET}}
          AWS_BUCKET_NAME: ${{secrets.AWS_BUCKET_NAME}}

      - name: Generate deployment package
        run: zip -r deploy.zip * .[^.]* -x "**node_modules**"

      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'

      - name: Beanstalk Deploy for app
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          application_name: mobile-api
          environment_name: ${{secrets.AWS_ENV_NAME}}
          region: us-east-1
          version_label: "e-learn-${{ steps.format-time.outputs.replaced }}"
          deployment_package: deploy.zip

      - name: Deployed!
        run: echo App deployed to ELB
